language: node_js
node_js:
- 4
script:
- npm run lint
- npm test
notifications:
  email: false
sudo: false
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
