sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
notifications:
  email: false
script:
  - npm run lint
  - npm test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
